title: ちょこトピβ
description: ちょこトピβのドキュメントページ
url: "https://weekend-llc.github.io"
baseurl: "/weekend.github.io"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
markdown: kramdown
relative_links:
  enabled: true
  collections: true 